# Use the official NGINX image for your platform
FROM --platform=linux/amd64 nginx:1.25-alpine

# Remove the default NGINX configuration
RUN rm -rf /etc/nginx/conf.d/default.conf

# Install inotify-tools
RUN apk add inotify-tools

# Copy the combined entrypoint script into the container
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Expose the ports Nginx will listen on
EXPOSE 80
EXPOSE 443

# Set the entrypoint script to run when the container starts
ENTRYPOINT ["/entrypoint.sh"]
